import 'package:flutter/material.dart';
import 'package:ressue_flutter/components/issue.dart';

class HomeIssuePage extends StatelessWidget {
  const HomeIssuePage({super.key});

  @override
  Widget build(BuildContext context) {
    return ListView(
      children: const [
        Issue(
          title: '수백억 들인 남북 \'화해의 상징\'..폭약에 와르르, 평화도 깨졌다',
          year: '4',
          month: '6',
          day: '16',
          reader: '14.1k',
          username: '밍밍한 광탈자',
          content: '탈북 삐라쟁이들과 조중동 미통닭이 날린거다....와 진짜 민폐집단들...전쟁유발자들',
        ),
        Issue(
          title: '수백억 들인 남북 \'화해의 상징\'..폭약에 와르르, 평화도 깨졌다',
          year: '4',
          month: '6',
          day: '16',
          reader: '14.1k',
          username: '밍밍한 광탈자',
          content: '탈북 삐라쟁이들과 조중동 미통닭이 날린거다....와 진짜 민폐집단들...전쟁유발자들',
        ),
        Issue(
          title: '수백억 들인 남북 \'화해의 상징\'..폭약에 와르르, 평화도 깨졌다',
          year: '4',
          month: '6',
          day: '16',
          reader: '14.1k',
          username: '밍밍한 광탈자',
          content: '탈북 삐라쟁이들과 조중동 미통닭이 날린거다....와 진짜 민폐집단들...전쟁유발자들',
        ),
        Issue(
          title: '수백억 들인 남북 \'화해의 상징\'..폭약에 와르르, 평화도 깨졌다',
          year: '4',
          month: '6',
          day: '16',
          reader: '14.1k',
          username: '밍밍한 광탈자',
          content: '탈북 삐라쟁이들과 조중동 미통닭이 날린거다....와 진짜 민폐집단들...전쟁유발자들',
        ),
        Issue(
          title: '수백억 들인 남북 \'화해의 상징\'..폭약에 와르르, 평화도 깨졌다',
          year: '4',
          month: '6',
          day: '16',
          reader: '14.1k',
          username: '밍밍한 광탈자',
          content: '탈북 삐라쟁이들과 조중동 미통닭이 날린거다....와 진짜 민폐집단들...전쟁유발자들',
        ),
        Issue(
          title: '수백억 들인 남북 \'화해의 상징\'..폭약에 와르르, 평화도 깨졌다',
          year: '4',
          month: '6',
          day: '16',
          reader: '14.1k',
          username: '밍밍한 광탈자',
          content: '탈북 삐라쟁이들과 조중동 미통닭이 날린거다....와 진짜 민폐집단들...전쟁유발자들',
        ),
        Issue(
          title: '수백억 들인 남북 \'화해의 상징\'..폭약에 와르르, 평화도 깨졌다',
          year: '4',
          month: '6',
          day: '16',
          reader: '14.1k',
          username: '밍밍한 광탈자',
          content: '탈북 삐라쟁이들과 조중동 미통닭이 날린거다....와 진짜 민폐집단들...전쟁유발자들',
        ),
        Issue(
          title: '수백억 들인 남북 \'화해의 상징\'..폭약에 와르르, 평화도 깨졌다',
          year: '4',
          month: '6',
          day: '16',
          reader: '14.1k',
          username: '밍밍한 광탈자',
          content: '탈북 삐라쟁이들과 조중동 미통닭이 날린거다....와 진짜 민폐집단들...전쟁유발자들',
        ),
        Issue(
          title: '수백억 들인 남북 \'화해의 상징\'..폭약에 와르르, 평화도 깨졌다',
          year: '4',
          month: '6',
          day: '16',
          reader: '14.1k',
          username: '밍밍한 광탈자',
          content: '탈북 삐라쟁이들과 조중동 미통닭이 날린거다....와 진짜 민폐집단들...전쟁유발자들',
        ),
        Issue(
          title: '수백억 들인 남북 \'화해의 상징\'..폭약에 와르르, 평화도 깨졌다',
          year: '4',
          month: '6',
          day: '16',
          reader: '14.1k',
          username: '밍밍한 광탈자',
          content: '탈북 삐라쟁이들과 조중동 미통닭이 날린거다....와 진짜 민폐집단들...전쟁유발자들',
        ),
        Issue(
          title: '수백억 들인 남북 \'화해의 상징\'..폭약에 와르르, 평화도 깨졌다',
          year: '4',
          month: '6',
          day: '16',
          reader: '14.1k',
          username: '밍밍한 광탈자',
          content: '탈북 삐라쟁이들과 조중동 미통닭이 날린거다....와 진짜 민폐집단들...전쟁유발자들',
        ),
        Issue(
          title: '수백억 들인 남북 \'화해의 상징\'..폭약에 와르르, 평화도 깨졌다',
          year: '4',
          month: '6',
          day: '16',
          reader: '14.1k',
          username: '밍밍한 광탈자',
          content: '탈북 삐라쟁이들과 조중동 미통닭이 날린거다....와 진짜 민폐집단들...전쟁유발자들',
        ),
        Issue(
          title: '수백억 들인 남북 \'화해의 상징\'..폭약에 와르르, 평화도 깨졌다',
          year: '4',
          month: '6',
          day: '16',
          reader: '14.1k',
          username: '밍밍한 광탈자',
          content: '탈북 삐라쟁이들과 조중동 미통닭이 날린거다....와 진짜 민폐집단들...전쟁유발자들',
        ),
        Issue(
          title: '수백억 들인 남북 \'화해의 상징\'..폭약에 와르르, 평화도 깨졌다',
          year: '4',
          month: '6',
          day: '16',
          reader: '14.1k',
          username: '밍밍한 광탈자',
          content: '탈북 삐라쟁이들과 조중동 미통닭이 날린거다....와 진짜 민폐집단들...전쟁유발자들',
        ),
        Issue(
          title: '수백억 들인 남북 \'화해의 상징\'..폭약에 와르르, 평화도 깨졌다',
          year: '4',
          month: '6',
          day: '16',
          reader: '14.1k',
          username: '밍밍한 광탈자',
          content: '탈북 삐라쟁이들과 조중동 미통닭이 날린거다....와 진짜 민폐집단들...전쟁유발자들',
        ),
      ],
    );
  }
}
